
package GamingPC_Pro_billing;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;


public class billSystem extends javax.swing.JFrame {

   
    public billSystem() {  // All methods that should run at the start should be here 
        initComponents();  /* In Java, the initComponents() method is used to initialize the components of a graphical user interface (GUI). 
                           It is typically called from the constructor of the class that contains the GUI. 
                           The initComponents() method is generated by the NetBeans IDE when you create a GUI using the GUI Builder. */
        billHead();
        
        
        
        
    }
    
    public void billtotable(){ //**to add data to the table**
    
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel)jTable1.getModel();
        
        
        model.addRow(new Object[]{
        proname.getText(),
        price.getText(),
        disc.getText(),
        disc2.getText(),
        qty.getText(),
        lastprice.getText(),
        total.getText()
                       
                 
        });  

         int sum = 0;
         
        for(int i = 0; i<jTable1.getRowCount(); i++){
        sum=sum+Integer.parseInt(jTable1.getValueAt(i,6).toString());
        subtotal.setText(Integer.toString(sum));
        
       
        
    }  

        
    }
      
    public void billHead(){
         bill.setText( "                         ----------Gaming PC Pro----------                        \n"
                     + "                      ~for a realistic gaming experience~                     \n"
                     + "                               No 96, Gall Road,                              \n" 
                     + "                                   Colombo                                  \n"
                     + "     tel : 011xxxxxxx | email : gamingpcpro@info.lk | web : www.gamingpcpro.lk    \n"            
                     + "    ___________________________________________________________________________    \n\n"
                     + "    (1) Product x Quantity\n" + "    (2) price\n" + "    (3) total\n"
                     + "    ___________________________________________________________________________    \n"); 
                     
                     
    
    }
    
   
        public void bill1(){
            bill.setText(bill.getText());
        
        }
        public void bill2(){
            bill.setText(bill.getText()+"\n"+"    (1)" + " " + proname.getText()+" x " +qty.getText()+"        "+ "    (2)" + " " + "Rs."+price.getText()+"        "+"    (3)"+ " " +"Rs." +total.getText()+"\n");
        
        }

    
    
    
     
    
    
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jDesktopPane1 = new javax.swing.JDesktopPane();
    jLabel18 = new javax.swing.JLabel();
    clearall = new javax.swing.JButton();
    add = new javax.swing.JButton();
    jLabel10 = new javax.swing.JLabel();
    total = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    lastprice = new javax.swing.JTextField();
    disc2 = new javax.swing.JTextField();
    jLabel17 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    proname = new javax.swing.JTextField();
    price = new javax.swing.JTextField();
    qty = new javax.swing.JTextField();
    disc = new javax.swing.JTextField();
    delete = new javax.swing.JButton();
    delete1 = new javax.swing.JButton();
    delete3 = new javax.swing.JButton();
    delete2 = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    bill = new javax.swing.JTextArea();
    add2 = new javax.swing.JButton();
    print = new javax.swing.JButton();
    jLabel14 = new javax.swing.JLabel();
    cash = new javax.swing.JTextField();
    balance = new javax.swing.JTextField();
    delete4 = new javax.swing.JButton();
    pay = new javax.swing.JButton();
    jLabel13 = new javax.swing.JLabel();
    subtotal = new javax.swing.JTextField();
    jLabel15 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    tdisc = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jLabel19 = new javax.swing.JLabel();
    jLabel21 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel22 = new javax.swing.JLabel();
    jLabel23 = new javax.swing.JLabel();
    jLabel25 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel20 = new javax.swing.JLabel();
    jLabel26 = new javax.swing.JLabel();
    jLabel27 = new javax.swing.JLabel();
    jLabel28 = new javax.swing.JLabel();
    jLabel29 = new javax.swing.JLabel();
    jLabel31 = new javax.swing.JLabel();
    jLabel32 = new javax.swing.JLabel();
    jLabel33 = new javax.swing.JLabel();
    jSeparator2 = new javax.swing.JSeparator();
    jLabel30 = new javax.swing.JLabel();
    jLabel34 = new javax.swing.JLabel();
    jLabel35 = new javax.swing.JLabel();
    jLabel36 = new javax.swing.JLabel();
    jLabel24 = new javax.swing.JLabel();
    jLabel38 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));
    setFont(new java.awt.Font("Dubai Medium", 0, 10)); // NOI18N
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel1.setBackground(new java.awt.Color(51, 102, 255));

    jDesktopPane1.setForeground(new java.awt.Color(251, 188, 16));
    jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    jDesktopPane1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 184, 501, -1));

    clearall.setBackground(new java.awt.Color(0, 0, 0));
    clearall.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
    clearall.setForeground(new java.awt.Color(204, 204, 204));
    clearall.setText("Clear All");
    clearall.setAlignmentX(0.5F);
    clearall.setFocusable(false);
    clearall.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    clearall.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    clearall.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        clearallActionPerformed(evt);
      }
    });
    jDesktopPane1.add(clearall, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 580, -1, -1));

    add.setBackground(new java.awt.Color(0, 0, 255));
    add.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
    add.setForeground(new java.awt.Color(255, 255, 255));
    add.setText("Add");
    add.setAlignmentX(0.5F);
    add.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addActionPerformed(evt);
      }
    });
    jDesktopPane1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 580, -1, -1));

    jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 27)); // NOI18N
    jLabel10.setForeground(new java.awt.Color(204, 255, 255));
    jLabel10.setText("Total (Rs) :");
    jLabel10.setAlignmentX(0.5F);
    jDesktopPane1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, -1, -1));

    total.setEditable(false);
    total.setBackground(new java.awt.Color(202, 181, 117));
    total.setFont(new java.awt.Font("Dubai Medium", 2, 22)); // NOI18N
    total.setForeground(new java.awt.Color(51, 51, 51));
    total.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    total.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        totalActionPerformed(evt);
      }
    });
    jDesktopPane1.setLayer(total, javax.swing.JLayeredPane.POPUP_LAYER);
    jDesktopPane1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 185, 40));

    jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 27)); // NOI18N
    jLabel12.setForeground(new java.awt.Color(204, 255, 255));
    jLabel12.setText("Last Price (Rs) :");
    jLabel12.setAlignmentX(0.5F);
    jDesktopPane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, -1, -1));

    lastprice.setEditable(false);
    lastprice.setBackground(new java.awt.Color(202, 181, 117));
    lastprice.setFont(new java.awt.Font("Dubai Medium", 2, 22)); // NOI18N
    lastprice.setForeground(new java.awt.Color(51, 51, 51));
    lastprice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    lastprice.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        lastpriceActionPerformed(evt);
      }
    });
    jDesktopPane1.setLayer(lastprice, javax.swing.JLayeredPane.POPUP_LAYER);
    jDesktopPane1.add(lastprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 185, 40));

    disc2.setEditable(false);
    disc2.setBackground(new java.awt.Color(202, 181, 117));
    disc2.setFont(new java.awt.Font("Dubai Medium", 2, 22)); // NOI18N
    disc2.setForeground(new java.awt.Color(51, 51, 51));
    disc2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    disc2.setPreferredSize(new java.awt.Dimension(3, 44));
    disc2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        disc2ActionPerformed(evt);
      }
    });
    jDesktopPane1.setLayer(disc2, javax.swing.JLayeredPane.POPUP_LAYER);
    jDesktopPane1.add(disc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 185, 40));

    jLabel17.setFont(new java.awt.Font("Tw Cen MT", 1, 27)); // NOI18N
    jLabel17.setForeground(new java.awt.Color(204, 255, 255));
    jLabel17.setText("Discount (Rs) :");
    jLabel17.setAlignmentX(0.5F);
    jDesktopPane1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, -1, -1));

    jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 27)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(204, 255, 255));
    jLabel8.setText("Discount (%) :");
    jLabel8.setAlignmentX(0.5F);
    jDesktopPane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));

    jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 27)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(204, 255, 255));
    jLabel9.setText("Quantity :");
    jLabel9.setAlignmentX(0.5F);
    jDesktopPane1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

    jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 27)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(204, 255, 255));
    jLabel7.setText("Price (Rs) :");
    jLabel7.setAlignmentX(0.5F);
    jDesktopPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 140, -1));

    jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 27)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(204, 255, 255));
    jLabel6.setText("Product Name :");
    jLabel6.setAlignmentX(0.5F);
    jDesktopPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

    jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(251, 188, 16));
    jLabel11.setText("Enter the product details here.");
    jDesktopPane1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 383, -1));

    jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 68)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("GAMING");
    jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, 90));

    proname.setBackground(new java.awt.Color(236, 236, 236));
    proname.setFont(new java.awt.Font("Dubai Medium", 0, 22)); // NOI18N
    proname.setForeground(new java.awt.Color(51, 51, 51));
    proname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    proname.setSelectionColor(new java.awt.Color(255, 255, 255));
    proname.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        pronameActionPerformed(evt);
      }
    });
    jDesktopPane1.setLayer(proname, javax.swing.JLayeredPane.POPUP_LAYER);
    jDesktopPane1.add(proname, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 290, 40));

    price.setBackground(new java.awt.Color(236, 236, 236));
    price.setFont(new java.awt.Font("Dubai Medium", 0, 22)); // NOI18N
    price.setForeground(new java.awt.Color(51, 51, 51));
    price.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    price.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        priceActionPerformed(evt);
      }
    });
    jDesktopPane1.setLayer(price, javax.swing.JLayeredPane.POPUP_LAYER);
    jDesktopPane1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 185, 40));

    qty.setBackground(new java.awt.Color(236, 236, 236));
    qty.setFont(new java.awt.Font("Dubai Medium", 0, 22)); // NOI18N
    qty.setForeground(new java.awt.Color(51, 51, 51));
    qty.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    qty.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        qtyActionPerformed(evt);
      }
    });
    jDesktopPane1.setLayer(qty, javax.swing.JLayeredPane.POPUP_LAYER);
    jDesktopPane1.add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 185, 40));

    disc.setBackground(new java.awt.Color(236, 236, 236));
    disc.setFont(new java.awt.Font("Dubai Medium", 0, 22)); // NOI18N
    disc.setForeground(new java.awt.Color(51, 51, 51));
    disc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    disc.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        discActionPerformed(evt);
      }
    });
    jDesktopPane1.setLayer(disc, javax.swing.JLayeredPane.POPUP_LAYER);
    jDesktopPane1.add(disc, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 185, 40));

    delete.setBackground(new java.awt.Color(0, 0, 0));
    delete.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
    delete.setForeground(new java.awt.Color(204, 204, 204));
    delete.setText("X");
    delete.setAlignmentX(0.5F);
    delete.setMaximumSize(new java.awt.Dimension(40, 40));
    delete.setMinimumSize(new java.awt.Dimension(40, 40));
    delete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteActionPerformed(evt);
      }
    });
    jDesktopPane1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1007, 231, 40, 40));

    delete1.setBackground(new java.awt.Color(0, 0, 0));
    delete1.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
    delete1.setForeground(new java.awt.Color(204, 204, 204));
    delete1.setText("X");
    delete1.setAlignmentX(0.5F);
    delete1.setMaximumSize(new java.awt.Dimension(40, 40));
    delete1.setMinimumSize(new java.awt.Dimension(40, 40));
    delete1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        delete1ActionPerformed(evt);
      }
    });
    jDesktopPane1.add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, 40, 40));

    delete3.setBackground(new java.awt.Color(0, 0, 0));
    delete3.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
    delete3.setForeground(new java.awt.Color(204, 204, 204));
    delete3.setText("X");
    delete3.setAlignmentX(0.5F);
    delete3.setMaximumSize(new java.awt.Dimension(40, 40));
    delete3.setMinimumSize(new java.awt.Dimension(40, 40));
    delete3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        delete3ActionPerformed(evt);
      }
    });
    jDesktopPane1.add(delete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, 40, 40));

    delete2.setBackground(new java.awt.Color(0, 0, 0));
    delete2.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
    delete2.setForeground(new java.awt.Color(204, 204, 204));
    delete2.setText("X");
    delete2.setAlignmentX(0.5F);
    delete2.setMaximumSize(new java.awt.Dimension(40, 40));
    delete2.setMinimumSize(new java.awt.Dimension(40, 40));
    delete2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        delete2ActionPerformed(evt);
      }
    });
    jDesktopPane1.add(delete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 380, 40, 40));

    jPanel2.setBackground(new java.awt.Color(255, 255, 255));
    jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jPanel2.setForeground(new java.awt.Color(255, 255, 255));

    bill.setColumns(20);
    bill.setFont(new java.awt.Font("Monospac821 BT", 0, 15)); // NOI18N
    bill.setRows(5);
    jScrollPane2.setViewportView(bill);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jDesktopPane1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1122, 396, 759, -1));

    add2.setBackground(new java.awt.Color(0, 0, 255));
    add2.setFont(new java.awt.Font("MV Boli", 1, 23)); // NOI18N
    add2.setForeground(new java.awt.Color(255, 255, 255));
    add2.setText("Add");
    add2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        add2ActionPerformed(evt);
      }
    });
    jDesktopPane1.add(add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 882, -1, -1));

    print.setBackground(new java.awt.Color(204, 0, 255));
    print.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
    print.setForeground(new java.awt.Color(204, 204, 204));
    print.setText("Print");
    print.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        printActionPerformed(evt);
      }
    });
    jDesktopPane1.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(1446, 895, -1, -1));

    jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 27)); // NOI18N
    jLabel14.setForeground(new java.awt.Color(204, 255, 255));
    jLabel14.setText("Cash (Rs) :");
    jDesktopPane1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 830, 140, -1));

    cash.setBackground(new java.awt.Color(236, 236, 236));
    cash.setFont(new java.awt.Font("Dubai Medium", 0, 22)); // NOI18N
    cash.setForeground(new java.awt.Color(51, 51, 51));
    cash.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    cash.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cashActionPerformed(evt);
      }
    });
    jDesktopPane1.setLayer(cash, javax.swing.JLayeredPane.POPUP_LAYER);
    jDesktopPane1.add(cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 827, 185, 40));

    balance.setEditable(false);
    balance.setBackground(new java.awt.Color(202, 181, 117));
    balance.setFont(new java.awt.Font("Dubai Medium", 2, 22)); // NOI18N
    balance.setForeground(new java.awt.Color(51, 51, 51));
    balance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    balance.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        balanceActionPerformed(evt);
      }
    });
    jDesktopPane1.setLayer(balance, javax.swing.JLayeredPane.POPUP_LAYER);
    jDesktopPane1.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 877, 185, 40));

    delete4.setBackground(new java.awt.Color(0, 0, 0));
    delete4.setFont(new java.awt.Font("Dubai Medium", 1, 18)); // NOI18N
    delete4.setForeground(new java.awt.Color(204, 204, 204));
    delete4.setText("X");
    delete4.setMaximumSize(new java.awt.Dimension(40, 40));
    delete4.setMinimumSize(new java.awt.Dimension(40, 40));
    delete4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        delete4ActionPerformed(evt);
      }
    });
    jDesktopPane1.add(delete4, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 827, 40, 40));

    pay.setBackground(new java.awt.Color(0, 153, 0));
    pay.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
    pay.setForeground(new java.awt.Color(255, 255, 255));
    pay.setText("Pay");
    pay.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        payActionPerformed(evt);
      }
    });
    jDesktopPane1.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 820, -1, -1));

    jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 27)); // NOI18N
    jLabel13.setForeground(new java.awt.Color(204, 255, 255));
    jLabel13.setText("Subtotal  (Rs) :");
    jDesktopPane1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 780, 180, -1));

    subtotal.setEditable(false);
    subtotal.setBackground(new java.awt.Color(202, 181, 117));
    subtotal.setFont(new java.awt.Font("Dubai Medium", 2, 22)); // NOI18N
    subtotal.setForeground(new java.awt.Color(51, 51, 51));
    subtotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    subtotal.setPreferredSize(new java.awt.Dimension(3, 44));
    subtotal.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        subtotalActionPerformed(evt);
      }
    });
    jDesktopPane1.setLayer(subtotal, javax.swing.JLayeredPane.POPUP_LAYER);
    jDesktopPane1.add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 777, 185, 40));

    jLabel15.setFont(new java.awt.Font("Tw Cen MT", 1, 27)); // NOI18N
    jLabel15.setForeground(new java.awt.Color(204, 255, 255));
    jLabel15.setText("Balance (Rs) :");
    jDesktopPane1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 880, -1, -1));

    jLabel16.setFont(new java.awt.Font("Tw Cen MT", 1, 27)); // NOI18N
    jLabel16.setForeground(new java.awt.Color(204, 255, 255));
    jLabel16.setText("Total Discount (Rs) :");
    jDesktopPane1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 930, -1, -1));

    tdisc.setEditable(false);
    tdisc.setBackground(new java.awt.Color(202, 181, 117));
    tdisc.setFont(new java.awt.Font("Dubai Medium", 2, 22)); // NOI18N
    tdisc.setForeground(new java.awt.Color(51, 51, 51));
    tdisc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jDesktopPane1.setLayer(tdisc, javax.swing.JLayeredPane.POPUP_LAYER);
    jDesktopPane1.add(tdisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 927, 185, 40));

    jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(251, 188, 16));
    jLabel5.setText("Summary.");
    jDesktopPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 160, 102, -1));

    jTable1.setBackground(new java.awt.Color(51, 102, 255));
    jTable1.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 16)); // NOI18N
    jTable1.setForeground(new java.awt.Color(255, 255, 255));
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Product Name", "Price (Rs)", "Discount (%)", "Discount (Rs)", "Quantity", "Last Price (Rs)", "Total (Rs)"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jTable1.setGridColor(new java.awt.Color(51, 51, 255));
    jTable1.setMaximumSize(new java.awt.Dimension(760, 138));
    jTable1.setMinimumSize(new java.awt.Dimension(760, 138));
    jTable1.setPreferredSize(new java.awt.Dimension(760, 138));
    jTable1.setShowHorizontalLines(false);
    jScrollPane1.setViewportView(jTable1);
    if (jTable1.getColumnModel().getColumnCount() > 0) {
      jTable1.getColumnModel().getColumn(0).setPreferredWidth(200);
      jTable1.getColumnModel().getColumn(1).setPreferredWidth(70);
      jTable1.getColumnModel().getColumn(2).setPreferredWidth(70);
      jTable1.getColumnModel().getColumn(4).setPreferredWidth(70);
      jTable1.getColumnModel().getColumn(6).setPreferredWidth(70);
    }

    jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1122, 240, 760, 138));

    jLabel19.setFont(new java.awt.Font("Microsoft YaHei", 0, 20)); // NOI18N
    jLabel19.setForeground(new java.awt.Color(251, 188, 16));
    jLabel19.setText("After adding details of all products,  you can add the cash.");
    jDesktopPane1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 700, 582, -1));

    jLabel21.setFont(new java.awt.Font("Impact", 0, 100)); // NOI18N
    jLabel21.setForeground(new java.awt.Color(255, 0, 0));
    jLabel21.setText("PRO");
    jDesktopPane1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 680, -1, -1));
    jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 34)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
    jLabel3.setText("For  a  Realistic  Gaming  Experience | ");
    jDesktopPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 13, -1, -1));

    jLabel4.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(153, 153, 153));
    jLabel4.setText("billing system");
    jDesktopPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 14, -1, -1));
    jDesktopPane1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 265, -1, -1));

    jLabel23.setFont(new java.awt.Font("Kristen ITC", 1, 68)); // NOI18N
    jLabel23.setForeground(new java.awt.Color(255, 51, 153));
    jLabel23.setText("PC");
    jDesktopPane1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, -1, 90));

    jLabel25.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
    jLabel25.setForeground(new java.awt.Color(255, 255, 255));
    jLabel25.setText("GAMING PC PRO ");
    jDesktopPane1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

    jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
    jDesktopPane1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, 261, 10));
    jDesktopPane1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 714, -1, -1));
    jDesktopPane1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(3696, 167, -1, -1));
    jDesktopPane1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\KRISH\\OneDrive\\Desktop\\Java Projects\\joystick.png")); // NOI18N
    jDesktopPane1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 13, 76, -1));
    jDesktopPane1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(2750, 416, 103, -1));

    jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\KRISH\\OneDrive\\Desktop\\Java Projects\\right-clicks.png")); // NOI18N
    jDesktopPane1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

    jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\KRISH\\OneDrive\\Desktop\\Java Projects\\right-clicks.png")); // NOI18N
    jDesktopPane1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 160, -1, -1));

    jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\KRISH\\OneDrive\\Desktop\\Java Projects\\right-clicks.png")); // NOI18N
    jDesktopPane1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 700, -1, -1));

    jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
    jDesktopPane1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 60, 577, 10));
    jDesktopPane1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 286, -1, -1));

    jLabel34.setIcon(new javax.swing.ImageIcon("C:\\Users\\KRISH\\OneDrive\\Desktop\\Java Projects\\gaming (1).png")); // NOI18N
    jDesktopPane1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 104, -1));
    jDesktopPane1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 160, -1, -1));

    jLabel36.setToolTipText("");
    jDesktopPane1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 580, -1, -1));

    jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\KRISH\\OneDrive\\Desktop\\Java Projects\\pc (1).png")); // NOI18N
    jDesktopPane1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

    jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\KRISH\\Downloads\\wallpaperflare.com_wallpaper (19).jpg")); // NOI18N
    jDesktopPane1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 3268, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
      .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 550, Short.MAX_VALUE))
    );

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 3280, 1630));

    setSize(new java.awt.Dimension(1914, 1080));
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_subtotalActionPerformed

  private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed

    float subtotalnum = 0,cashnum = 0,balancenum = 0;

    subtotalnum = Integer.parseInt(subtotal.getText());
    cashnum = Integer.parseInt(cash.getText());

    balancenum = cashnum - subtotalnum;

    balance.setText(Integer.toString((int) balancenum));

    int sum1 = 0;

    for(int k = 0; k<jTable1.getRowCount(); k++){
      sum1=sum1+Integer.parseInt(jTable1.getValueAt(k,3).toString());
      tdisc.setText(Integer.toString(sum1));

    }

  }//GEN-LAST:event_payActionPerformed

  private void delete4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete4ActionPerformed
    cash.setText("");
  }//GEN-LAST:event_delete4ActionPerformed

  private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_cashActionPerformed

  private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
    try {
      bill.print();

    } catch (PrinterException ex) {
      Logger.getLogger(billSystem.class.getName()).log(Level.SEVERE, null, "Sorry! Cannot print!");
    }
  }//GEN-LAST:event_printActionPerformed

  private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed
    bill.setText(bill.getText()+ "\n\n--------------------------------------------------------------------------------"+"\n\n * Sub Total         :    Rs.       " + subtotal.getText() +"\n * Cash              :    Rs.       " + cash.getText() + "\n * Balance           :    Rs.       " + balance.getText() + "\n * Total Disocunt    :    Rs.       " + tdisc.getText() +"\n\n\n" + "  `-`-`-`-`-`-`-`-`-`-`-`-`-`THANK YOU COME AGAIN!-`-`-`-`-`-`-`-`-`-`-`-`-`-");
    
    // Get the current local time.
        LocalDateTime currentTime = LocalDateTime.now();

        // Print the current local time.
        //System.out.println("time : " + currentTime);
        //bill.setText(currentTime.getText(now());
  }//GEN-LAST:event_add2ActionPerformed

  private void delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete2ActionPerformed
    disc.setText("");
  }//GEN-LAST:event_delete2ActionPerformed

  private void delete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete3ActionPerformed
    qty.setText("");
  }//GEN-LAST:event_delete3ActionPerformed

  private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
    price.setText("");
  }//GEN-LAST:event_delete1ActionPerformed

        // **Delete the data**
  private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
    proname.setText("");
  }//GEN-LAST:event_deleteActionPerformed

  private void discActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_discActionPerformed

  private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_qtyActionPerformed

  private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_priceActionPerformed

  private void pronameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pronameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_pronameActionPerformed

  private void disc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disc2ActionPerformed
    
  }//GEN-LAST:event_disc2ActionPerformed

  private void lastpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastpriceActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_lastpriceActionPerformed

  private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_totalActionPerformed

  private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
    // This is Add button.

    int pricenum, qtynum;
    float totalnum,discnum,lastpricenum,disc2num; // **because they can be decimal values**

    pricenum = Integer.parseInt(price.getText());
    discnum = Integer.parseInt(disc.getText());
    qtynum = Integer.parseInt(qty.getText());

    disc2num = (discnum*pricenum)/100;
    lastpricenum = pricenum - disc2num;

    totalnum = (int) (lastpricenum*qtynum); // **typecasted

    total.setText(Integer.toString((int) totalnum)); // **typecasted**
    lastprice.setText(Integer.toString((int) lastpricenum)); // **typecasted**
    disc2.setText(Integer.toString((int) disc2num)); // **typecasted**

    // **add data to the table**
    billtotable();

    bill1();
    bill2();

    

    // **delete the data**
    deleteActionPerformed();

  }//GEN-LAST:event_addActionPerformed

  private void clearallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearallActionPerformed
    // This is Clear All button
    proname.setText("");
    price.setText("");
    disc.setText("");
    qty.setText("");
    cash.setText("");
    disc2.setText("");

    lastprice.setText("");
    total.setText("");
    balance.setText("");
    tdisc.setText("");

  }//GEN-LAST:event_clearallActionPerformed

  private void balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_balanceActionPerformed

    
    
    
   
    public static void main(String args[]) throws Exception {
      
      String str = "javax.swing.plaf.nimbus.NimbusLookAndFeel";
      
      UIManager.setLookAndFeel(str);
      
      new billSystem();
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billSystem().setVisible(true);
            }
        });
        
        
        
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton add;
  private javax.swing.JButton add2;
  private javax.swing.JTextField balance;
  private javax.swing.JTextArea bill;
  private javax.swing.JTextField cash;
  private javax.swing.JButton clearall;
  private javax.swing.JButton delete;
  private javax.swing.JButton delete1;
  private javax.swing.JButton delete2;
  private javax.swing.JButton delete3;
  private javax.swing.JButton delete4;
  private javax.swing.JTextField disc;
  private javax.swing.JTextField disc2;
  private javax.swing.JDesktopPane jDesktopPane1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel20;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel22;
  private javax.swing.JLabel jLabel23;
  private javax.swing.JLabel jLabel24;
  private javax.swing.JLabel jLabel25;
  private javax.swing.JLabel jLabel26;
  private javax.swing.JLabel jLabel27;
  private javax.swing.JLabel jLabel28;
  private javax.swing.JLabel jLabel29;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel30;
  private javax.swing.JLabel jLabel31;
  private javax.swing.JLabel jLabel32;
  private javax.swing.JLabel jLabel33;
  private javax.swing.JLabel jLabel34;
  private javax.swing.JLabel jLabel35;
  private javax.swing.JLabel jLabel36;
  private javax.swing.JLabel jLabel38;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JTable jTable1;
  private javax.swing.JTextField lastprice;
  private javax.swing.JButton pay;
  private javax.swing.JTextField price;
  private javax.swing.JButton print;
  private javax.swing.JTextField proname;
  private javax.swing.JTextField qty;
  private javax.swing.JTextField subtotal;
  private javax.swing.JTextField tdisc;
  private javax.swing.JTextField total;
  // End of variables declaration//GEN-END:variables

    private void deleteActionPerformed() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /*private void clear(){
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/

    private static class jTable1 {

        public jTable1() {
        }

        private jTable1(DefaultTableModel tableModel) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private int getRowCount() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
